// Problem 5 test file

const assert = require('assert')
const resolve = require('./app5')

assert.strictEqual(resolve([1, 3, 5, 6], 5), 2)
assert.strictEqual(resolve([1, 3, 5, 6], 2), 1)
assert.strictEqual(resolve([1, 3, 5, 6], 7), 4)
assert.strictEqual(resolve([1, 3, 5, 6], 0), 0)
assert.strictEqual(resolve([1], 0), 0)
assert.throws(() => resolve([1,2,5], '2'))
assert.throws(() => resolve([1,2,5], {}))
assert.throws(() => resolve([1,2,5], null))
assert.throws(() => resolve([1,2,5], true))
assert.throws(() => resolve([1,2,5], undefined))
assert.throws(() => resolve([1,2,5], NaN))
assert.throws(() => resolve([1,2,NaN], 2))
assert.throws(() => resolve({}, 2))
assert.throws(() => resolve({}, 2))
assert.throws(() => resolve([1,2,Infinity], 2))
assert.throws(() => resolve([1,2,3], Infinity))
assert.throws(() => resolve())
assert.throws(() => resolve(null))
assert.throws(() => resolve(undefined))
assert.throws(() => resolve(NaN))
assert.throws(() => resolve(true))
assert.throws(() => resolve(Infinity))
assert.throws(() => resolve(() => {}))
assert.throws(() => resolve(1n))