// Problem 3 test file

const assert = require('assert')
const resolve = require('./app3')

assert.strictEqual(resolve('())'), false)
assert.strictEqual(resolve('))(('), false)
assert.strictEqual(resolve('()'), true)
assert.strictEqual(resolve('()[]{}'), true)
assert.strictEqual(resolve('(]'), false)
assert.strictEqual(resolve('([)]'), false)
assert.strictEqual(resolve('{[]}'), true)
assert.strictEqual(resolve('()()[][]{}{}'), true)
assert.strictEqual(resolve('()[{()()}][]{[()()]}'), true)
assert.throws(() => resolve(''))
assert.throws(() => resolve('string'))
assert.throws(() => resolve())
assert.throws(() => resolve(null))
assert.throws(() => resolve(undefined))
assert.throws(() => resolve(NaN))
assert.throws(() => resolve(true))
assert.throws(() => resolve(() => {}))
assert.throws(() => resolve(Infinity))
assert.throws(() => resolve(1n))