// Problem 1 test file

const assert = require('assert')
const resolve = require('./app1')

assert.strictEqual(resolve('III'), 3)
assert.strictEqual(resolve('IV'), 4)
assert.strictEqual(resolve('IX'), 9)
assert.strictEqual(resolve('XIV'), 14)
assert.strictEqual(resolve('XIX'), 19)
assert.strictEqual(resolve('XL'), 40)
assert.strictEqual(resolve('LVIII'), 58)
assert.strictEqual(resolve('MCMXCIV'), 1994)
assert.throws(() => resolve('IIII'))
assert.throws(() => resolve('XM'))
assert.throws(() => resolve(''))
assert.throws(() => resolve('XXIB'))
assert.throws(() => resolve(2))
assert.throws(() => resolve(true))
assert.throws(() => resolve([]))
assert.throws(() => resolve({}))
assert.throws(() => resolve(Infinity))
assert.throws(() => resolve(NaN))
assert.throws(() => resolve(1n))
assert.throws(() => resolve(() => {}))
assert.throws(() => resolve(null))